# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 11:21
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def add_core(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site_domain = 'site.django-first.com'
    site_name = 'Company Centralizer'
    siteid = getattr(settings, 'SITE_ID', 1)
    if Site.objects.exists:
        actual_site = Site.objects.get(
            pk=siteid
        )
        actual_site.domain = site_domain
        actual_site.name = site_name
        actual_site.save()
    else:
        actual_site = Site(
            pk=siteid,
            domaine=site_domain,
            name=site_name
        )
        actual_site.save()

def remove_core(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    actual_site = Site.objects.get(
        pk=getattr(settings, 'SITE_ID', 1)
    )
    actual_site.domain = 'example.com'
    actual_site.name = 'example.com'
    actual_site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_core,
            remove_core,
        )
    ]
