# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 11:34
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

FLATPAGES = [{
    "title": "About",
    "url": "/about/",
    "content": "<p>This is the content</p>"
}]

def add_flat_data(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    Site = apps.get_model('sites', 'Site')
    siteid = getattr(settings, 'SITE_ID', 1)
    actual_site = Site.objects.get(pk=siteid)
    for pg in FLATPAGES:
        newpage = FlatPage.objects.create(
            title=pg['title'],
            url=pg['url'],
            content=pg['content']
        )
    newpage.sites.add(actual_site)

def remove_flat_data(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    for pg in FLATPAGES:
        delpage = pg.objects.get(url=pg['url'])
    delpage.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_core_data'),
        ('flatpages', '0001_initial')
    ]

    operations = [
        migrations.RunPython(
            add_flat_data,
            remove_flat_data
        )
    ]
