# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centralizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=63)),
                ('art_slug', models.SlugField(help_text='Label for URL composition', max_length=63, unique_for_month='pub_date')),
                ('content', models.TextField()),
                ('added', models.DateField(auto_now_add=True, verbose_name='date when the article was added')),
                ('companies', models.ManyToManyField(related_name='articles', to='centralizer.Company')),
                ('tags', models.ManyToManyField(related_name='articles', to='centralizer.Tag')),
            ],
            options={
                'ordering': ['-added', 'title'],
                'verbose_name': 'blog article',
                'get_latest_by': 'added',
            },
        ),
    ]
