# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_slug',
            field=models.SlugField(help_text='Label for URL composition', max_length=63, unique_for_month='added'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='articleid'),
        ),
        migrations.AlterField(
            model_name='article',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='articles', to='centralizer.Company'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='centralizer.Tag'),
        ),
    ]
