# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170105_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='articleid'),
        ),
    ]
