# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 22:55
from __future__ import unicode_literals

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

ARTICLES = [{
        "title": "New Tech",
        "art_slug": "new-tech",
        "content": "It is coming folks",
        "tags": ["mobile", "django", "machine learning"],
        "companies" : "robotul-rozaliu"
    }]

def add_article(apps, schema_editor):
    Article = apps.get_model(
        'blog', 'Article'
        )
    Company = apps.get_model(
        'centralizer', 'Company'
        )
    Tag = apps.get_model(
        'centralizer', 'Tag'
        )
    for art in ARTICLES:
        new_art = Article.objects.create(
            title=art['title'],
            art_slug=art['art_slug'],
            content=art['content']
            )
        test_quer = Company.objects.get(company_slug=art['companies'])
        if test_quer:
            new_art.companies.add(test_quer)
            for tag in art['tags']:
                try:
                    minitag = Tag.objects.get(tag_slug=tag)
                except ObjectDoesNotExist:
                    minitag = None
                if minitag:
                    new_art.tags.add(minitag)
                    
def remove_article(apps, schema_editor):
    Article = apps.get_model(
        'blog', 'Article'
        )
    for art in ARTICLES:
        delart = Article.objects.get(art_slug=art['art_slug'])
        delart.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_data'),
        ('centralizer', '0004_companies_data')
    ]

    operations = [
        migrations.RunPython(
            add_article,
            remove_article
            )
    ]
