# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170105_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_slug',
            field=models.SlugField(help_text='Label for URL composition', max_length=63, unique_for_month='added'),
        ),
    ]
