# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articles_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'added', 'ordering': ['-added', 'title'], 'permissions': (('view_future_article', 'Can view unpublished Article'),), 'verbose_name': 'blog article'},
        ),
    ]
