# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 12:35
from __future__ import unicode_literals

from django.db import migrations

ARTICLES = {
    "title": "New Tech",
    "art_slug": "new-tech",
    "content": "It is coming folks",
    "tags": ["mobile", "django", "machine-learning"],
    "companies": "robotul-rozaliu"
}

def add_article(apps, schema_editor):
    Article = apps.get_model(
        'blog', 'Article'
    )
    for art in ARTICLES:
        Article.objects.create(
            title=art['title'],
            art_slug=art['art_slug'],
            content=art['content']
        )
        art.companies.add(Article.objects.get(company_slug=art['companies']))
        for tag in art['tags']:
            art.tags.add(Article.objects.get(tag_slug=tag))

def remove_article(apps, schema_editor):
    Article = apps.get_model(
        'blog', 'Article'
    )
    for art in ARTICLES:
        delart = Article.objects.get(art_slug=art['art_slug'])
        delart.delete()

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_auto_20170126_1117'),
        ('centralizer', '0004_companies'),
    ]

    operations = [
        migrations.RunPython(
            add_article,
            remove_article
        )
    ]
