# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatednews',
            name='news_slug',
            field=models.SlugField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='compid'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='companies', to='centralizer.Tag'),
        ),
        migrations.AlterField(
            model_name='relatednews',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='centralizer.Company'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='tagid'),
        ),
        migrations.AlterUniqueTogether(
            name='relatednews',
            unique_together=set([('news_slug', 'company')]),
        ),
    ]
