# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='compid'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='tagid'),
        ),
    ]
