# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 11:20
from __future__ import unicode_literals

from django.db import migrations

def add_tag(apps, schema_editor):
    #get_model gets the historical model
    NewTag = apps.get_model('centralizer', 'Tag')
    for tag_name, tag_slug in TAGS:
        NewTag.objects.create(
            tagname=tag_name,
            tag_slug = tag_slug
        )

def remove_tag(apps, schema_editor):
    NewTag = apps.get_model('centralizer', 'Tag')
    #bad idea --> NewTag.objects.all().delete()
    for _, slugs in TAGS:
        thetag = NewTag.objects.get(tag_slug=slugs)
        thetag.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0002_auto_20170105_1314'),
    ]

    operations = [
        migrations.RunPython(
            add_tag,
            remove_tag
        )
    ]

TAGS = (
    #tag name, tag slug
    ("machine learning", "machine-learning"),
)

