# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 11:57
from __future__ import unicode_literals
from datetime import date
from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

COMPANIES = [{
    "company_name": "Robotul Rozaliu",
    "company_slug": "robotul-rozaliu",
    "description": "Vrem sa-l facem cu fundul roz",
    "founded_date": date(2011, 5, 21),
    "tags": ["mobile", "web", "machine-learning"],
    "website": "http://robotulrozaliu.com/",
}]

def add_company(apps, schema_editor):
    Company = apps.get_model(
        'centralizer', 'Company'
    )
    Tag = apps.get_model(
        'centralizer', 'Tag'
    )
    for comp in COMPANIES:
        new_company = Company.objects.create(
            company_name=comp['company_name'],
            company_slug=comp['company_slug'],
            description=comp['description'],
            founded_date=comp['founded_date'],
            website=comp['website'])
        for tag in comp['tags']:            
            try:
                argf = Tag.objects.get(tag_slug=tag)
            except ObjectDoesNotExist:
                argf = None
            if argf:
                new_company.tags.add(argf)

def remove_company(apps, schema_editor):
    Company = apps.get_model( 
        "centralizer", "Company"
    ) 
    for comp in COMPANIES:  
        delcomp = Company.objects.get(
            company_slug = comp['slug']
        )
        delcomp.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0003_tag_data'),
    ]

    operations = [
        migrations.RunPython(
            add_company,
            remove_company
        )
    ]
