# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist


def add_slug(apps, schema_editor):
    Related = apps.get_model(
        'centralizer', 'RelatedNews'
    )
    interog = Related.objects.all()
    for rel in interog:
        potential_slug = slugify(rel.title)
        
        try:
            howmany = (
                Related.objects.filter(
                    company=rel.company,
                    news_slug__startswith=potential_slug
                ).count())
        except ObjectDoesNotExist:
            howmany = 0
        if howmany > 1:
            string_len = (SLUG_LENGTH - len(str(howmany)))
            rel.news_slug = "{}-{}".format(potential_slug[:string_len - 1], howmany + 1)
        else:
            rel.news_slug = potential_slug
            
        rel.news_slug = potential_slug
        rel.save()

def remove_slug(apps, schema_editor):
    Related = apps.get_model(
        'centralizer', 'RelatedNews'
    )
    Related.objects.update(news_slug='')

SLUG_LENGTH = 63

class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0004_companies_data'),
    ]

    operations = [
        migrations.RunPython(
            add_slug,
            reverse_code=remove_slug
        ),
   ]
