# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 09:58
from __future__ import unicode_literals
from datetime import date
from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

RELATED = [{
    'title': 'Check this out',
    'pub_date': date(2014, 6, 9),
    'newslink': "https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf",
    'company': 'robotul-rozaliu'
}]

def add_related(apps, schema_editor):
    Related = apps.get_model(
        'centralizer', 'RelatedNews'
    )
    Company = apps.get_model(
        'centralizer', 'Company'
    )
    for rel in RELATED:
        try:
            company = Company.objects.get(company_slug=rel['company'])
        except ObjectDoesNotExist:
            company = None
        if company:
            #new_news.company.add(company)
            new_news = Related.objects.create(
                title=rel['title'],
                pub_date=rel['pub_date'],
                newslink=rel['newslink'],
                company=Company.objects.get(company_slug=rel['company'])
            )

def remove_related(apps, schema_editor):
    Related = apps.get_model(
        'centralizer', 'RelatedNews'
    )
    for rel in RELATED:
        delrel = Related.objects.get()
        delrel.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0004_companies'),
    ]

    operations = [
        migrations.RunPython(
            add_related,
            remove_related
        )
    ]
