# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0005_related_news_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatednews',
            name='company',
        ),
        migrations.AddField(
            model_name='relatednews',
            name='company',
            field=models.ManyToManyField(related_name='related_news', to='centralizer.Company'),
        ),
    ]
