# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centralizer', '0007_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatednews',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='centralizer.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='relatednews',
            unique_together=set([('news_slug', 'company')]),
        ),
        migrations.RemoveField(
            model_name='relatednews',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='relatednews',
            unique_together=set([('news_slug','company')])
        )
    ]
